declare const usCodes: Readonly<{
    ak: "Alaska";
    al: "Alabama";
    ar: "Arkansas";
    as: "American Samoa";
    az: "Arizona";
    ca: "California";
    co: "Colorado";
    ct: "Connecticut";
    de: "Delaware";
    dc: "District of Columbia";
    fl: "Florida";
    ga: "Georgia";
    gu: "Guam";
    hi: "Hawaii";
    id: "Idaho";
    il: "Illinois";
    in: "Indiana";
    ia: "Iowa";
    ks: "Kansas";
    ky: "Kentucky";
    la: "Louisiana";
    me: "Maine";
    md: "Maryland";
    ma: "Massachusetts";
    mi: "Michigan";
    mn: "Minnesota";
    ms: "Mississippi";
    mo: "Missouri";
    mp: "Nortern Mariana Islands";
    mt: "Montana";
    ne: "Nebraska";
    nv: "Nevada";
    nh: "New Hampshire";
    nj: "New Jersey";
    ny: "New York";
    nc: "North Carolina";
    nd: "North Dakota";
    oh: "Ohio";
    ok: "Oklahoma";
    or: "Oregon";
    pa: "Pennsylvania";
    pr: "Puerto Rico";
    ri: "Rhode Island";
    sc: "South Carolina";
    sd: "South Dakota";
    tn: "Tennessee";
    tx: "Texas";
    ut: "Utah";
    vt: "Vermont";
    va: "Virginia";
    vi: "U.S. Virgin Islands";
    wa: "Washington";
    wv: "West Virginia";
    wi: "Wisconsin";
    wy: "Wyoming";
}>;
declare const canadaCodes: Readonly<{
    ab: "Alberta";
    bc: "British Columbia";
    mb: "Manitoba";
    nb: "New Brunswick";
    nl: "Newfoundland and Labrador";
    ns: "Nova Scotia";
    nt: "Northwest Territories";
    nu: "Nunavut";
    on: "Ontario";
    pe: "Prince Edward Island";
    qc: "Quebec";
    sk: "Saskatchewan";
    yt: "Yukon";
}>;
declare const ukCodes: Readonly<{
    eng: "England";
    nir: "Northern Ireland";
    sct: "Scotland";
    wls: "Wales";
}>;
declare const australiaCodes: Readonly<{
    act: "Australian Capital Territory";
    nsw: "New South Wales";
    nt: "Northern Territory";
    qld: "Queensland";
    sa: "South Australia";
    tas: "Tasmania";
    vic: "Victoria";
    wa: "Western Australia";
}>;
export { usCodes, canadaCodes, ukCodes, australiaCodes };
